JS_RECORDS = [
    {
        "key": "js.react.peer_dependency",
        "title": "React peer dependency conflict",
        "summary": "npm could not resolve the install because React and a UI library required different major versions.",
        "root_cause": "The project upgraded React before all peer-dependent packages supported that version.",
        "fix_steps": "Check the peer dependency ranges, upgrade the dependent package or pin React to a supported version, then regenerate the lockfile.",
        "confidence": 0.86,
        "tags": ["javascript", "npm", "peer-dependency", "react"],
        "errors": [
            "npm ERR! ERESOLVE unable to resolve dependency tree peer react",
            "Found: react@19 Could not resolve peer react@^18 from component library",
            "node peer dependency conflict react during npm install",
        ],
    },
    {
        "key": "ts.undefined.property",
        "title": "Undefined property read in component",
        "summary": "A TypeScript component tried to read a nested property before async data had loaded.",
        "root_cause": "The render path assumed the API response was present on the first render.",
        "fix_steps": "Guard the loading state, narrow the response type, and add a test for the empty or pending data state.",
        "confidence": 0.83,
        "tags": ["frontend", "typescript", "undefined"],
        "errors": [
            "TypeError: Cannot read properties of undefined (reading 'name')",
            "Cannot read property 'items' of undefined in Dashboard.tsx",
            "runtime crash cannot read properties of undefined while rendering list",
        ],
    },
    {
        "key": "ts.tsconfig.path_alias",
        "title": "TypeScript path alias not resolved",
        "summary": "The compiler could not resolve imports using the app path alias.",
        "root_cause": "tsconfig paths were changed without matching the bundler or test runner alias configuration.",
        "fix_steps": "Align tsconfig paths with Vite or Jest aliases, restart the TS server, and run the typecheck command.",
        "confidence": 0.81,
        "tags": ["alias", "tsconfig", "typescript"],
        "errors": [
            "Cannot find module '@/components/Button' or its corresponding type declarations",
            "tsconfig path alias @/* not resolving in vite build",
            "TypeScript compile error cannot find module using absolute import",
        ],
    },
    {
        "key": "js.vite.env_prefix",
        "title": "Vite env variable unavailable",
        "summary": "Frontend code read an env value that Vite did not expose to the browser bundle.",
        "root_cause": "The variable was missing the VITE_ prefix or was not present in the local .env file.",
        "fix_steps": "Rename browser-exposed variables with the VITE_ prefix, update .env examples, and restart the dev server.",
        "confidence": 0.84,
        "tags": ["env", "frontend", "vite", "web"],
        "errors": [
            "import.meta.env.API_URL is undefined in Vite app",
            "missing env var VITE_API_URL during frontend startup",
            "Vite dev server cannot read API base URL from environment",
        ],
    },
    {
        "key": "js.webpack.loader",
        "title": "Webpack loader missing for CSS",
        "summary": "The build failed when Webpack encountered a CSS file without a matching loader.",
        "root_cause": "A new stylesheet import was added before css-loader and style-loader were configured.",
        "fix_steps": "Add or restore the CSS loader rule, ensure the loaders are installed, and rerun the production build.",
        "confidence": 0.78,
        "tags": ["build", "css", "javascript", "webpack"],
        "errors": [
            "Module parse failed: Unexpected token You may need an appropriate loader to handle this file type",
            "webpack build failed loading styles.css no loader configured",
            "CSS import causes module parse failed in webpack production build",
        ],
    },
    {
        "key": "js.lockfile.stale",
        "title": "Stale lockfile after package update",
        "summary": "CI installed a different package graph than local development because the lockfile was not regenerated.",
        "root_cause": "package.json changed without committing the matching package-lock.json update.",
        "fix_steps": "Run the package manager install command, commit the regenerated lockfile, and rerun CI from a clean checkout.",
        "confidence": 0.8,
        "tags": ["ci", "javascript", "lockfile", "npm"],
        "errors": [
            "npm ci can only install packages when package.json and package-lock.json are in sync",
            "CI failed because lock file's dependencies do not satisfy package.json",
            "package-lock out of date after dependency update",
        ],
    },
    {
        "key": "ts.type_mismatch_api",
        "title": "API response type mismatch",
        "summary": "TypeScript rejected code after the backend response shape changed.",
        "root_cause": "The frontend type still expected the old field name from the API contract.",
        "fix_steps": "Update the shared response type or adapter mapping, adjust usages, and add a contract-shaped fixture test.",
        "confidence": 0.82,
        "tags": ["api", "contract", "typescript"],
        "errors": [
            "Property 'userName' does not exist on type 'UserResponse'",
            "TS2339: Property 'data' does not exist on type ApiResult",
            "frontend compile failed after backend schema renamed displayName",
        ],
    },
]
