PYTHON_RECORDS = [
    {
        "key": "python.numpy.missing",
        "title": "Numpy import missing in pytest",
        "summary": "pytest failed because numpy was not installed in the active project environment.",
        "root_cause": "The shell was using a virtual environment that did not include the project's numeric dependency set.",
        "fix_steps": "Install numpy through the project package manager, resync the environment, and rerun the failing pytest target.",
        "confidence": 0.92,
        "tags": ["dependency", "import", "pytest", "python"],
        "errors": [
            "ModuleNotFoundError: No module named 'numpy'",
            "ImportError while importing test module tests/test_math.py: No module named 'numpy'",
            "pytest import error ModuleNotFoundError numpy missing from venv",
        ],
    },
    {
        "key": "python.requests.missing",
        "title": "Requests dependency missing from worker",
        "summary": "The worker crashed on startup because requests was absent from the runtime environment.",
        "root_cause": "The dependency was used by a helper module but was not declared in project dependencies.",
        "fix_steps": "Add requests to the managed dependencies, rebuild or sync the environment, and restart the worker.",
        "confidence": 0.88,
        "tags": ["dependency", "import", "python", "worker"],
        "errors": [
            "ModuleNotFoundError: No module named 'requests'",
            "worker failed during import: No module named requests",
            "python import requests missing after fresh uv sync",
        ],
    },
    {
        "key": "python.pytest.client_fixture",
        "title": "Pytest client fixture missing",
        "summary": "A test requested the client fixture before conftest.py registered it.",
        "root_cause": "The application test client fixture was either renamed or not exported from the local test setup.",
        "fix_steps": "Define the client fixture in conftest.py, import the app factory, and keep the fixture scope aligned with the tests.",
        "confidence": 0.9,
        "tags": ["fixture", "pytest", "python", "tests"],
        "errors": [
            "fixture 'client' not found",
            "pytest fixture client not found in tests/test_api.py",
            "E fixture 'client' not found available fixtures: app, monkeypatch",
        ],
    },
    {
        "key": "python.pip.resolution_conflict",
        "title": "Pip dependency resolution conflict",
        "summary": "A package install failed because two dependencies required incompatible versions of the same package.",
        "root_cause": "The lockfile constraints allowed mutually incompatible transitive dependency ranges.",
        "fix_steps": "Inspect the resolver conflict, pin compatible versions in project dependencies, regenerate the lockfile, and rerun tests.",
        "confidence": 0.84,
        "tags": ["dependency", "pip", "python", "resolver"],
        "errors": [
            "ERROR: ResolutionImpossible: for help visit pip dependency conflict",
            "pip install failed because package versions have conflicting dependencies",
            "dependency conflict: fastapi requires pydantic <2 but project installed pydantic 2",
        ],
    },
    {
        "key": "python.venv.mismatch",
        "title": "Wrong virtual environment selected",
        "summary": "The command used a different Python interpreter than the one with the project dependencies installed.",
        "root_cause": "The active shell or IDE interpreter pointed outside the repository virtual environment.",
        "fix_steps": "Select the project .venv interpreter, run the command through uv, and confirm python -c imports the dependency.",
        "confidence": 0.86,
        "tags": ["environment", "python", "venv"],
        "errors": [
            "ModuleNotFoundError: No module named 'pytest' after installing requirements",
            "python points to global interpreter instead of project .venv",
            "tests fail in Cursor terminal because selected interpreter is not the uv environment",
        ],
    },
    {
        "key": "python.nonetype.attribute",
        "title": "Unexpected None response object",
        "summary": "A Python request handler attempted to access an attribute on None after an upstream lookup missed.",
        "root_cause": "The code assumed a database or API lookup always returned an object and skipped the missing-result branch.",
        "fix_steps": "Handle the missing result explicitly, return a useful error response, and add a regression test for the absent record.",
        "confidence": 0.8,
        "tags": ["api", "nonetype", "python"],
        "errors": [
            "AttributeError: 'NoneType' object has no attribute 'id'",
            "AttributeError: 'NoneType' object has no attribute 'json'",
            "handler crashed because user lookup returned None",
        ],
    },
    {
        "key": "python.alembic.missing_revision",
        "title": "Alembic migration revision missing",
        "summary": "Database migration startup failed because the configured revision was not present locally.",
        "root_cause": "The branch expected a migration file that was not pulled, generated, or merged correctly.",
        "fix_steps": "Pull the latest migrations, verify alembic heads, regenerate the missing revision if needed, and rerun upgrades.",
        "confidence": 0.82,
        "tags": ["alembic", "database", "migration", "python"],
        "errors": [
            "Can't locate revision identified by '8f31c2a9'",
            "alembic.util.exc.CommandError: Can't locate revision",
            "database startup failed because alembic revision is missing",
        ],
    },
]
