WEB_RECORDS = [
    {
        "key": "web.cors.localhost",
        "title": "Local API blocked by CORS",
        "summary": "The browser blocked a frontend request because the API did not allow the local dev origin.",
        "root_cause": "The backend CORS allowlist omitted the frontend dev server origin.",
        "fix_steps": "Add the local frontend origin to CORS configuration, include credentials only when needed, and restart the API.",
        "confidence": 0.9,
        "tags": ["api", "cors", "frontend", "web"],
        "errors": [
            "Access to fetch at 'http://localhost:8000/api' from origin 'http://localhost:5173' has been blocked by CORS policy",
            "CORS blocked by API missing Access-Control-Allow-Origin header",
            "web cors api blocked while calling local backend from vite",
        ],
    },
    {
        "key": "web.auth.token_expired",
        "title": "Expired auth token rejected",
        "summary": "Authenticated API calls returned 401 because the frontend kept using an expired access token.",
        "root_cause": "The token refresh path did not update storage before retrying protected requests.",
        "fix_steps": "Refresh the token before retry, persist the new access token, and clear auth state when refresh fails.",
        "confidence": 0.84,
        "tags": ["auth", "token", "web"],
        "errors": [
            "401 Unauthorized token expired",
            "auth token mismatch after refresh protected route returns 401",
            "API rejected request because bearer token is expired",
        ],
    },
    {
        "key": "web.schema.camel_snake",
        "title": "Frontend/backend schema casing mismatch",
        "summary": "The frontend rendered empty values because the API returned snake_case fields while UI code expected camelCase.",
        "root_cause": "The response adapter did not normalize backend field names at the API boundary.",
        "fix_steps": "Normalize the response in one adapter, update the TypeScript type, and add a fixture covering the backend payload.",
        "confidence": 0.82,
        "tags": ["api", "contract", "frontend", "web"],
        "errors": [
            "user.displayName is undefined but API returned display_name",
            "frontend backend schema mismatch snake_case camelCase",
            "React page blank because response field user_name is not mapped to userName",
        ],
    },
    {
        "key": "web.cookie.samesite",
        "title": "Session cookie not sent cross-site",
        "summary": "Browser requests were unauthenticated because the session cookie was not included across frontend and API origins.",
        "root_cause": "Cookie SameSite, Secure, or credentials settings did not match the local cross-origin setup.",
        "fix_steps": "Set fetch credentials intentionally, configure SameSite=None and Secure for HTTPS, and use a local proxy when developing over HTTP.",
        "confidence": 0.79,
        "tags": ["auth", "cookie", "session", "web"],
        "errors": [
            "session cookie not sent with fetch request credentials include",
            "login succeeds but next API request is unauthenticated",
            "Set-Cookie ignored because SameSite=None missing Secure attribute",
        ],
    },
    {
        "key": "web.proxy.target",
        "title": "Dev proxy target points at wrong backend",
        "summary": "Frontend requests hit the wrong service because the dev proxy target was stale.",
        "root_cause": "The local proxy config still pointed at an old API port or container hostname.",
        "fix_steps": "Update the dev server proxy target, confirm the backend health endpoint, and restart the frontend dev server.",
        "confidence": 0.78,
        "tags": ["dev-server", "proxy", "vite", "web"],
        "errors": [
            "Vite proxy error ECONNREFUSED /api/users",
            "frontend dev proxy points to wrong backend port",
            "web app receives 502 from local API proxy after backend port changed",
        ],
    },
    {
        "key": "web.mixed_content",
        "title": "HTTPS page blocked HTTP API call",
        "summary": "The browser blocked an API request because an HTTPS frontend tried to call an HTTP endpoint.",
        "root_cause": "The deployed frontend was configured with an insecure API base URL.",
        "fix_steps": "Use the HTTPS API endpoint in environment config, update deployment secrets, and verify browser network requests.",
        "confidence": 0.8,
        "tags": ["deployment", "env", "https", "web"],
        "errors": [
            "Mixed Content: The page at https://app.example.com was loaded over HTTPS but requested an insecure resource",
            "browser blocked HTTP API call from HTTPS frontend",
            "production env API_URL uses http and causes mixed content failure",
        ],
    },
]
